language: php

php:
  - hhvm
  - 7.1
  - 7.0
  - 5.6
  - 5.5

env:
  global:
    - COMPOSER=composer-ci.json
  matrix:
    - DB=mysql
    - DB=pgsql
    - DB=sqlite

matrix:
  exclude:
    - php: hhvm
      env: DB=pgsql

branches:
  only:
    - master
    - gh-pages
    - /^feature\/.+$/

install:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.1"
  - travis_retry composer global require "codeception/codeception:2.2.*"
  - travis_retry composer install --no-interaction --prefer-dist
#  - ln -s `pwd`/vendor/bower-asset `pwd`/vendor/bower

before_script:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS audit_test;" -uroot; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS audit_test;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database audit_test;" -U postgres; fi
  - cd tests
  - php codeception/_app/yii migrate/up --interactive=0
  - php codeception/_app/yii migrate/up --migrationPath=../src/migrations --interactive=0
  - ~/.composer/vendor/bin/codecept build

script:
  - ~/.composer/vendor/bin/codecept run --coverage-html --coverage-xml

after_script:
  - php ../vendor/bin/ocular code-coverage:upload --format=php-clover codeception/_output/coverage.xml

after_failure:
  - cat codeception/_app/runtime/logs/*
  - cat codeception/_output/*

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b8a97760936530897759
    on_success: change
    on_failure: always
    on_start: false
